### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by ChangJoo-Park** [ChangJoo-Park/what-to-do#34]
Nordstrom 
https://www.youtube.com/watch?v=szr0ezLyQHY&list=WL&index=1

IDEO
https://www.youtube.com/watch?v=gjz_o2318eQ

**Comment by rkdgusrnrlrl** [comment]
IDEO 잘 봤습니다. ㅎㅎㅎ 
제품(어플리케이션)도 저런 식으로 만들어지면 좋겠죠??

**Comment by ChangJoo-Park** [comment]
가능할까요? ㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
가능 하지 않을까요? 뭐 창주님 같은 사람 10명만 있으면 될 것 같습니다 :) ㅎㅎ

**Comment by ChangJoo-Park** [comment]
그러면 큰일날걸요 ㅋㅋㅋㅋㅋ
